version: 2.1

jobs:
  test-linux:
    machine:
      image: ubuntu-2204:current   # Dedicated VM; 24.04 is fine if/when available
    resource_class: medium
    steps:

      - checkout

      - run:
          name: Install kernel extras + tools
          command: |
            sudo apt-get update
            # Extras usually contain vcan.ko and can-isotp.ko on Ubuntu generic kernels
            sudo apt-get install -y "linux-modules-extra-$(uname -r)" can-utils build-essential

      - run:
          name: Enable SocketCAN (vcan) + try ISO-TP
          command: |
            set -euxo pipefail
            sudo modprobe can || true
            sudo modprobe can_raw || true
            sudo modprobe vcan || true
            sudo ip link add dev vcan0 type vcan || true
            sudo ip link set vcan0 up
            ip -details link show vcan0
            # Prefer kernel ISO-TP if present
            if grep -q '^CONFIG_CAN_ISOTP=y' /boot/config-$(uname -r) || sudo modprobe can-isotp 2>/dev/null; then
              echo "COPT=-DUDS_TP_ISOTP_SOCK" >> $BASH_ENV
              echo "USING=kernel isotp" >> $BASH_ENV
            else
              echo "COPT=-DUDS_TP_ISOTP_C_SOCKETCAN" >> $BASH_ENV
              echo "USING=userspace isotp-c" >> $BASH_ENV
            fi
            source $BASH_ENV
            echo "Transport: $USING"

      # Optional smoke test (only if kernel ISO-TP succeeded)
      - run:
          name: ISO-TP smoke test (optional)
          when: on_success
          command: |
            set -euxo pipefail
            if [ "${USING}" = "kernel isotp" ]; then
              isotprecv -s 0x700 -d 0x701 -l vcan0 &
              sleep 1
              printf "01 0C\n" | isotpsend -s 0x701 -d 0x700 vcan0
              sleep 1
              pkill isotprecv || true
            else
              echo "Skipping kernel ISO-TP smoke test (using isotp-c)."
            fi

      - run:
          name: Bazel tests
          command: |
            set -euxo pipefail
            bazel test //test:all --test_output=errors

workflows:
  version: 2
  build:
    jobs:
      - test-linux