version: 2.1
orbs:
  codecov: codecov/codecov@5.4.3


jobs:
  linux-transport-unit-tests-and-coverage:
    machine:
      image: ubuntu-2204:current   # Dedicated VM; 24.04 is fine if/when available
    resource_class: medium
    steps:

      - checkout

      - run:
          name: Install kernel extras + tools
          command: |
            sudo apt-get update
            # Extras usually contain vcan.ko and can-isotp.ko on Ubuntu generic kernels
            sudo apt-get install -y "linux-modules-extra-$(uname -r)" can-utils build-essential curl

      - run:
          name: Install Bazel (Bazelisk)
          command: |
            set -euxo pipefail
            curl -L https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-amd64 -o bazelisk
            sudo mv bazelisk /usr/local/bin/bazel
            sudo chmod +x /usr/local/bin/bazel
            bazel version


      - run:
          name: Enable SocketCAN (vcan) + try ISO-TP
          command: |
            set -euxo pipefail
            sudo modprobe can || true
            sudo modprobe can_raw || true
            sudo modprobe vcan || true
            sudo ip link add dev vcan0 type vcan || true
            sudo ip link set vcan0 up
            ip -details link show vcan0

      # Optional smoke test (only if kernel ISO-TP succeeded)
      - run:
          name: ISO-TP smoke test (optional)
          when: on_success
          command: |
            set -euxo pipefail
            isotprecv -s 0x700 -d 0x701 -l vcan0 &
            sleep 1
            printf "01 0C\n" | isotpsend -s 0x701 -d 0x700 vcan0
            sleep 1
            pkill isotprecv || true

      - run:
          name: Run tests with coverage
          command: |
            set -euxo pipefail
            bazel coverage \
              --combined_report=lcov \
              --instrumentation_filter='^//:(iso14229)$' \
              --experimental_collect_code_coverage_for_generated_files \
              --test_output=errors \
              //test:all
            cp "$(bazel info output_path)/_coverage/_coverage_report.dat" coverage.lcov
            sed -E -i 's#^SF:bazel-out/.*/iso14229.c#SF:iso14229.c#' coverage.lcov
            sed -E -i 's#^SF:bazel-out/.*/iso14229.h#SF:iso14229.h#' coverage.lcov
            ls -l coverage.lcov

      - codecov/upload:

workflows:
  version: 2
  build:
    jobs:
      - linux-transport-unit-tests-and-coverage