name: Bug Report
description: File a bug report.
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: |
        Please complete this checklist. 
      options:
        - label: I've read the [**No AI / No LLM Policy**](https://github.com/driftregion/iso14229/blob/master/CONTRIBUTING.md#no-ai--no-llm-policy) and understand I may be blocked from the repository if it is violated
          required: true
  - type: textarea
    attributes:
      label: "Bug Description"
      description: "Provide a clear summary of the issue. What happened? What did you expect would happen? Attach code, CAN logs, console output which demonstrates the bug."
      value: |
        # What Happened:

        # What I Expected:

    validations:
      required: true
  - type: input 
    attributes:
      label: "UDS_LIB_VERSION"
      description: "Copy the library version here. It is at the top of iso14229.h"
      placeholder: "x.y.z"
    validations:
      required: true
