# cc_binary(
#     name = "client_multiserver",
#     srcs = [
#         "main.c",
#         "server1.c",
#         "server2.c",
#     ],
#     deps = [
#         "//:iso14229",
#         "//:tp_mock",
#     ],
#     defines = [
#         "UDS_TP=UDS_TP_CUSTOM",
#     ]
# )