name: 'Setup Bazel Cache'
description: 'Set up Bazel caching for faster builds'
runs:
  using: 'composite'
  steps:
    - name: Cache Bazel
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/bazel
        key: ${{ runner.os }}-bazel-${{ hashFiles('**/MODULE.bazel', '**/*.bzl', '**/BUILD*') }}
        restore-keys: |
          ${{ runner.os }}-bazel-