name: unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: lint
      run: CHECK_FORMAT=1 ./tools/run_clang_format.sh
      continue-on-error: true

    - name: run unit tests
      run: bazel test //test:all --test_tag_filters=-vcan
    
  build-linux-clang:
    runs-on: ubuntu-22.04

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: run ultra_strict
      run: |
        sudo apt-get update 
        sudo apt-get install -y libtinfo5
        bazel build --repo_env=CC=clang --repo_env=CXX=clang++ //test:ultra_strict
  
  fuzz-replay-linux-clang:
    runs-on: ubuntu-22.04

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: run coverage
      run: |
        sudo apt-get update 
        sudo apt-get install -y libtinfo5
        ./scripts/2_replay_corpus.sh
    
    - name: upload coverage to Codecov
      run: |
        curl -Os https://cli.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov upload-process -t $CODECOV_TOKEN -F fuzz
    
  unittest-windows:
    runs-on: windows-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: run unit tests
      run: bazel test //test:all --verbose_failures --test_output=all 


  build-arduino:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: Install Arduino CLI
      uses: arduino/setup-arduino-cli@v2

    - name: build
      run: |
        arduino-cli core install arduino:samd
        arduino-cli lib install CAN
        arduino-cli -b arduino:samd:mkrwifi1010 compile examples/arduino_server/main 


  build-esp32:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.2
        target: esp32
        path: 'examples/esp32_server'