name: coverage

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pull-requests: write

jobs:
  linux-fuzz-coverage:
    runs-on: ubuntu-22.04

    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha || github.sha }}

    - name: Debug commit info
      run: |
        echo "=== Commit Debug Info ==="
        echo "Current HEAD: $(git rev-parse HEAD)"
        echo "PR head SHA: ${{ github.event.pull_request.head.sha }}"
        echo "GitHub SHA: ${{ github.sha }}"

    - name: Setup Bazel
      uses: bazel-contrib/setup-bazel@0.15.0
      with:
        bazelisk-cache: true
        disk-cache: ${{ github.workflow }}
        repository-cache: true

    - name: run coverage
      run: |
        ./scripts/2_replay_corpus.sh

    - name: upload coverage to Codecov
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        # Verify coverage file exists
        if [ ! -f coverage.lcov ]; then
          echo "Error: coverage.lcov file not found"
          exit 1
        fi
        echo "Coverage file size: $(wc -l < coverage.lcov) lines"
        # Download and run codecov
        curl -Os https://cli.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov --verbose upload-process --fail-on-error -t $CODECOV_TOKEN -F fuzz --file coverage.lcov --name "GitHub Actions Fuzz Coverage" --commit-sha $(git rev-parse HEAD) --report-code fuzz-report